# -*- coding: utf-8 -*-
"""터렛_최대RPM_계산기.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pXNCrrV_ZAiW1OZkq0pJvHqOI7pxVY1A
"""

import numpy as np
import matplotlib.pyplot as plt

def quadratic_from_3points(p1, p2, p3):
    x1, y1 = p1
    x2, y2 = p2
    x3, y3 = p3

    A = np.array([
        [x1**2, x1, 1],
        [x2**2, x2, 1],
        [x3**2, x3, 1]
    ], dtype=float)

    b = np.array([y1, y2, y3], dtype=float)

    a, b_coef, c = np.linalg.solve(A, b)
    return a, b_coef, c

#x가 세로축, y가 가로축, 여기에 입력!
p1 = (0, 0)
p2 = (100,3)
p3 = (140, 6)

a, b_coef, c = quadratic_from_3points(p1, p2, p3)

# 그래프
plt.figure(figsize=(8, 5))

# 곡선 그리기용 x 범위
x_vals = np.linspace(0, 150, 400)
y_vals = a*x_vals**2 + b_coef*x_vals + c

plt.figure(figsize=(8,5))

# 2차 곡선
plt.plot(x_vals, y_vals, label='Quadratic curve')

# 점 3개 표시
plt.scatter(
    [p1[0], p2[0], p3[0]],
    [p1[1], p2[1], p3[1]],
    color='red',
    label='Given points'
)
plt.xlabel('x')
plt.ylabel('y')
plt.title('Quadratic through 3 points')
plt.grid(True)
plt.legend()
plt.show()

print(f"y = {a:.8f}x^2 + {b_coef:.8f}x + {c:.8f}")

# 함수들 정의

def y(x):
    return a*x**2 + b_coef*x + c

def dy_dx(x):
    return 2*a*x + b_coef

def d2y_dx2(x):
    return 2*a  # 2차식이라 상수

def curvature_radius(x):
    return (1 + dy_dx(x)**2)**1.5 / abs(d2y_dx2(x))


# 4) 꼭짓점과 최소 곡률반경

x_vertex = -b_coef / (2*a)
y_vertex = y(x_vertex)
R_min = curvature_radius(x_vertex)

print(f"꼭짓점 x = {x_vertex:.4f}")
print(f"꼭짓점 y = {y_vertex:.4f}")
print(f"최소 곡률반경 R_min = {R_min:.4f}")

# 필요한 마그누스 힘 계산
m = 0.0027   # 탁구공 질량 [kg]
v = 8.0      # 공 속도 [m/s]:: 입력
R = R_min/100

def magnus_force(x):
    return m * v**2 / R

F_max = magnus_force(x_vertex)
print(f"가장 많이 휘는 지점에서 필요한 마그누스 힘 F_max = {F_max:.6f} N")

# CL 구하기
rho = 1.2          # 공기 밀도 [kg/m^3]
r_ball = 0.02      # 탁구공 반지름 [m]
R_wheel = 0.03  # wheel radius (m)
A = np.pi * r_ball**2   # 단면적 [m^2]

CL = (2 * F_max) / (rho * A * v**2)
print(f"CL = {CL:.4f}")

# spin ratio, 조정 필요
S = CL / 0.4

# 2. 공 각속도 (rad/s)
omega = S * v / r_ball

# 3. ball RPM
ball_RPM = omega * 60 / (2 * np.pi)

# 4. wheel surface speed 차이
# -----------------------------

delta_v = 2 * r_ball * omega

# 평균 속도 조건
# v = (v1 + v2) / 2

v1 = v + delta_v/2
v2 = v - delta_v/2

# 5. wheel RPM
rpm1 = v1 * 60 / (2 * np.pi * R_wheel)
rpm2 = v2 * 60 / (2 * np.pi * R_wheel)

rpm_diff = abs(rpm1 - rpm2)

# 결과 출력
print(f"Spin ratio S = {S:.3f}")

print("\nBall spin")
print(f"omega = {omega:.2f} rad/s")
print(f"ball RPM = {ball_RPM:.0f} RPM")

print("\nWheel surface speeds")
print(f"v1 = {v1:.2f} m/s")
print(f"v2 = {v2:.2f} m/s")

print("\nWheel RPM")
print(f"wheel1 RPM = {rpm1:.0f}")
print(f"wheel2 RPM = {rpm2:.0f}")
print(f"RPM difference = {rpm_diff:.0f}")